#define LV_VER_RES 480
#define LV_HOR_RES 320

// Touchscreen pins
#define XPT2046_IRQ 36  // T_IRQ
#define XPT2046_MOSI 32 // T_DIN
#define XPT2046_MISO 39 // T_OUT
#define XPT2046_CLK 25  // T_CLK
#define XPT2046_CS 33   // T_CS

#define PREF_ID_DOOR "PREF_ID_DOOR"

#define PREF_SSID "PREF_SSID"
#define PREF_SSID_PWD "PREF_PASSWORD"

#define PREF_IP_MQTT "PREF_IP_MQTT"

// LED PIN
#define LED_GREEN_PIN 17
#define LED_BLUE_PIN 16

#define MQTT_SERVER "192.168.0.118"
#define MQTT_PORT 1883
#define MQTT_TOPIC "door/qr"
#define MQTT_USERNAME "esp32"
#define MQTT_PASSWORD "esp32"

#define FROM_SERVER "SERVER"
#define FROM_ESP "ESP"

#define UPDATE_TOKEN "UPDATE_TOKEN"
#define UPDATE_MAC "UPDATE_MAC"
#define SET_ID_DOOR "SET_ID_DOOR"
#define ACCESS_DOOR "ACCESS_DOOR"
#define CHECK_TOKEN "CHECK_TOKEN"
#define RESPONSE_CHECK_TOKEN "RESPONSE_CHECK_TOKEN"