#define MQTT_SERVER "192.168.0.118"
#define MQTT_PORT 1883
#define MQTT_TOPIC "door/qr"
#define MQTT_USERNAME "esp32"
#define MQTT_PASSWORD "esp32"


#define FROM_SERVER "SERVER"
#define FROM_ESP "ESP"

#define UPDATE_TOKEN "UPDATE_TOKEN"
#define UPDATE_MAC "UPDATE_MAC"
#define SET_ID_DOOR "SET_ID_DOOR"
#define ACCESS_DOOR "ACCESS_DOOR"
#define CHECK_TOKEN "CHECK_TOKEN"
#define RESPONSE_CHECK_TOKEN "RESPONSE_CHECK_TOKEN"